CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Blog" (
    "ID" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Content" character varying(205) NOT NULL,
    CONSTRAINT "PK_Blog" PRIMARY KEY ("ID")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241123114759_InitialBlogs', '8.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Blog" ADD "OwnerID" bigint NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241126112821_BlogOwner', '8.0.11');

COMMIT;

