services:
  receptionist:
    image: blogreceptionist
    pull_policy: build
    build:
      context: ./BlogReceptionist
      dockerfile: ./BlogReceptionist/Dockerfile
    environment:
      - USERURL=http://userservice:8080
      - MQURL=rabbitMQChannel
      - REDISURL=redisService
    ports:
      - "5291:8080"
    depends_on:
      userService:
        condition: service_healthy
      blogService:
        condition: service_healthy

  userService:
    image: userservice
    pull_policy: build
    build:
      context: ./UserServer
      dockerfile: ./UserServer/Dockerfile
    environment:
      - DATABASEURL=mySQLDatabase
      - APPSECRET=secher
    ports:
      - "8001:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/ping"] # do not use , "||" !!!!!!
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 5s

  blogService:
    image: blogservice
    pull_policy: build
    build:
      context: ./BlogServer
      dockerfile: ./BlogServer/Dockerfile
    environment:
      - DATABASEURL=postgresDatabase
      - MQURL=rabbitMQChannel
    depends_on:
      rabbitMQChannel:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "sh", "-c", "pwd && [ -e healthy.txt ] && exit 0 || exit 5"]
      interval: 4s
      timeout: 25s
      retries: 5
      start_period: 3s

  postgresDatabase:
    image: postgres:17.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./BlogServer/BlogServer/SQLScript/:/docker-entrypoint-initdb.d/:ro

  rabbitMQChannel:
    image: rabbitmq
    ports:
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 8s

  mySQLDatabase:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
    volumes:
      - ./UserServer/UserServer/SQLScript/initUser.sql:/docker-entrypoint-initdb.d/initUser.sql:ro

  redisService:
    image: redis:7
    ports:
      - "6379:6379"
