services:
  userService:
    image: userservice
    pull_policy: build
    build:
      context: ./UserServer
      dockerfile: ./UserServer/Dockerfile
    environment:
      - DATABASEURL=mySQLDatabase
    ports:
      - "8080:8080"
      - "8081:8081"
      - "5159:5159"
  postgresDatabase:
    image: postgres:17.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
  rabbitMQChannel:
    image: rabbitmq:4-alpine
    ports:
      - "5672:5672"
  mySQLDatabase:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
  redisService:
    image: redis:7
    ports:
      - "6379:6379"
