@api_url=http://localhost:8001

GET {{api_url}}/api/user
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNvaW5jaWRlbmNlIiwiaWQiOiIxMSIsImV4cCI6MTczMjc4MDczNH0.fxwt-QJ7md4_Uh14KUGJGxbnt0HLtLtkTt18Dkxlcdg
Content-Type: application/json

###
GET {{api_url}}/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzI2MDQ2OTAsImF1ZCI6ImNvaW5jaWRlbmNlIn0.5k0sgxvioq5TspFkjDLDzF_SUxKIV7nfucivNB1Oz3E
Content-Type: application/json

###
GET {{api_url}}/api/user/id/2

###
GET {{api_url}}/api/user/coincidence
###

DELETE http://localhost:8001/api/user/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImliazkwOCIsImlkIjoiMiIsImV4cCI6MTczMjk1MDEwMn0.670PkqsDs3noUbZyl0mAUM026EAt-iw_tXABYnJsXuE
