@api_url=https://localhost:7275

PUT {{api_url}}/api/user/13
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImliazkwOCIsImlkIjoiMTMiLCJleHAiOjE3MzI3ODE4MjZ9.7PDzJNdwcFThXdji5Smm9eCRDMt_MH9DXdmpaNviOVs
Content-Type: application/json

"stringsss"

###