@apiURL = http://localhost:5291/api/user

GET {{apiURL}}
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImliazkwOCIsImlkIjoiMiIsImV4cCI6MTczMjk0NzA3NX0.CdJQ0PLUXIW5aMRAjoIPwpZAqWf_GVdaTvnAQEv5CRc
Content-Type: application/json

GET {{apiURL}}/id/11 HTTP/1.1

###
GET {{apiURL}}/id/13 HTTP/1.1

###
GET {{apiURL}}/coincidence HTTP/1.1
